format ="""
$directory $git_branch $git_status
$character 
"""
# Inserts a blank line between shell prompts
add_newline = true

scan_timeout = 10

[git_branch]
always_show_remote = true
format = "[on](light fg:#dddecf) [$branch](fg:#e69875)"


[git_status]
format       = "$ahead$behind$staged"
ahead        = "[⇡](bold fg:#caccbe)"
behind       = "[⇣](bold fg:#caccbe)"
staged       = "[++](bold fg:#caccbe)"

[directory]
truncation_length = 1 
truncate_to_repo = false
format = "[$path](bold fg:#e67e80)"

[character]
format = "$symbol"
success_symbol = "[❯](bold #b2c98f)"
error_symbol = "[❯](bold #e67e80)"
