format ="""
$directory $git_branch $git_status
$character 
"""
# Inserts a blank line between shell prompts
add_newline = true

scan_timeout = 10

[git_branch]
always_show_remote = true
format = "[on](light fg:#fdfff1) [$branch](fg:#fd971f)"


[git_status]
format       = "$ahead$behind$staged"
ahead        = "[⇡](bold fg:#c0c1b5)"
behind       = "[⇣](bold fg:#919288)"
staged       = "[++](bold fg:#6e7066)"

[directory]
truncation_length = 1 
truncate_to_repo = false
format = "[$path](bold fg:#f92672)"

[character]
format = "$symbol"
success_symbol = "[❯](bold #a6e22e)"
error_symbol = "[❯](bold #66d9ef)"
