## name: evergarden (hard)
## author: comfysage
## license: GPL-3.0
## blurb: a comfy colorscheme for cozy morning coding

[colors.primary]
background = "#1c2225"
foreground = "#dddecf"
dim_foreground = "#94aaa0"
bright_foreground = "#dddecf"

[colors.cursor]
text = "#171c1f"
cursor = "#E67E80"

[colors.vi_mode_cursor]
text = "#171c1f"
cursor = "#E67E80"

[colors.search.matches]
foreground = "#e69875"
background = "#171c1f"

[colors.search.focused_match]
foreground = "#171c1f"
background = "#e69875"

[colors.footer_bar]
foreground = "#839e9a"
background = "#171c1f"

[colors.hints.start]
foreground = "#171c1f"
background = "#dbbc7f"

[colors.hints.end]
foreground = "#171c1f"
background = "#94aaa0"

[colors.selection]
text = "#dddecf"
background = "#3d494d"

[colors.normal]
black = "#1c2225"
red = "#e67e80"
green = "#b2c98f"
yellow = "#dbbc7f"
blue = "#9bb5cf"
magenta = "#e3a8d1"
cyan = "#93c9a1"
white = "#dddecf"

[colors.bright]
black = "#313b40"
red = "#e67e80"
green = "#b2c98f"
yellow = "#dbbc7f"
blue = "#9bb5cf"
magenta = "#e3a8d1"
cyan = "#93c9a1"
white = "#94aaa0"

[colors.dim]
black = "#1c2225"
red = "#e67e80"
green = "#b2c98f"
yellow = "#dbbc7f"
blue = "#9bb5cf"
magenta = "#e3a8d1"
cyan = "#93c9a1"
white = "#dddecf"
